name: CARE
channels:
  - conda-forge
  - defaults
dependencies:
  # - _libgcc_mutex=0.1
  # - _openmp_mutex=4.5
  # - aom=3.9.1
  # - blas=1.1
  # - blinker=1.6.2
  # - bottleneck=1.3.7
  # - brotli=1.1.0
  # - brotli-bin=1.1.0
  # - brotli-python=1.0.9
  # - bzip2=1.0.8
  # - c-ares=1.33.1
  # - ca-certificates=2024.8.30
  # - cairo=1.18.0
  # - certifi=2024.8.30
  # - cffi=1.17.1
  # - charset-normalizer=3.3.2
  # - click=8.1.7
  # - colorama=0.4.6
  # - contourpy=1.2.0
  # - cycler=0.12.1
  # - dav1d=1.2.1
  # - dbus=1.13.18
  # - eigen=3.4.0
  # - expat=2.6.3
  # - ffmpeg=7.0.2
  # - filelock=3.13.1
  - flask=3.0.3
  # - font-ttf-dejavu-sans-mono=2.37
  # - font-ttf-inconsolata=2.001
  # - font-ttf-source-code-pro=2.030
  # - font-ttf-ubuntu=0.83
  # - fontconfig=2.14.2
  # - fonts-anaconda=1
  # - fonts-conda-ecosystem=1
  # - fonttools=4.51.0
  # - freeglut=3.4.0
  # - freetype=2.12.1
  # - fribidi=1.0.10
  # - fsspec=2024.6.1
  # - giflib=5.2.2
  # - glib=2.82.1
  # - glib-tools=2.82.1
  # - gmp=6.3.0
  # - gnutls=3.6.13
  # - graphite2=1.3.14
  # - gst-plugins-base=1.14.0
  # - gstreamer=1.14.1
  # - h2=4.1.0
  # - harfbuzz=9.0.0
  # - hdf5=1.14.3
  # - hpack=4.0.0
  # - hyperframe=6.0.1
  # - icu=75.1
  # - idna=3.10
  # - imath=3.1.12
  # - itsdangerous=2.2.0
  # - jasper=4.2.4
  # - jinja2=3.1.4
  # - kiwisolver=1.4.4
  # - krb5=1.21.3
  # - lame=3.100
  # - lcms2=2.16
  # - ld_impl_linux-64=2.40
  # - lerc=4.0.0
  # - libabseil=20240116.2
  # - libaec=1.1.3
  # - libasprintf=0.22.5
  # - libass=0.17.3
  # - libblas=3.9.0
  # - libbrotlicommon=1.1.0
  # - libbrotlidec=1.1.0
  # - libbrotlienc=1.1.0
  # - libcblas=3.9.0
  # - libclang=19.1.0
  # - libclang13=19.1.0
  # - libcups=2.3.3
  # - libcurl=8.10.1
  # - libdeflate=1.21
  # - libdrm=2.4.123
  # - libedit=3.1.20230828
  # - libegl=1.7.0
  # - libev=4.33
  # - libexpat=2.6.3
  # - libffi=3.4.4
  # - libgcc=14.1.0
  # - libgcc-ng=14.1.0
  # - libgettextpo=0.22.5
  # - libgfortran=14.1.0
  # - libgfortran-ng=14.1.0
  # - libgfortran5=14.1.0
  # - libgl=1.7.0
  # - libglib=2.82.1
  # - libglu=9.0.0
  # - libglvnd=1.7.0
  # - libglx=1.7.0
  # - libgomp=14.1.0
  # - libhwloc=2.11.1
  # - libiconv=1.17
  # - libjpeg-turbo=3.0.3
  # - liblapack=3.9.0
  # - liblapacke=3.9.0
  # - libllvm14=14.0.6
  # - libllvm19=19.1.0
  # - libnghttp2=1.58.0
  # - libnsl=2.0.1
  # - libopenblas=0.3.28
  # - libopencv=4.10.0
  # - libopenvino=2024.4.0
  # - libopenvino-auto-batch-plugin=2024.4.0
  # - libopenvino-auto-plugin=2024.4.0
  # - libopenvino-hetero-plugin=2024.4.0
  # - libopenvino-intel-cpu-plugin=2024.4.0
  # - libopenvino-intel-gpu-plugin=2024.4.0
  # - libopenvino-intel-npu-plugin=2024.4.0
  # - libopenvino-ir-frontend=2024.4.0
  # - libopenvino-onnx-frontend=2024.4.0
  # - libopenvino-paddle-frontend=2024.4.0
  # - libopenvino-pytorch-frontend=2024.4.0
  # - libopenvino-tensorflow-frontend=2024.4.0
  # - libopenvino-tensorflow-lite-frontend=2024.4.0
  # - libopus=1.3.1
  # - libpciaccess=0.18
  # - libpng=1.6.44
  # - libpq=16.4
  # - libprotobuf=4.25.3
  # - libsqlite=3.46.1
  # - libssh2=1.11.0
  # - libstdcxx=14.1.0
  # - libstdcxx-ng=14.1.0
  # - libtiff=4.7.0
  # - libtorch=2.4.0
  # - libuuid=2.38.1
  # - libuv=1.48.0
  # - libva=2.22.0
  # - libvpx=1.14.1
  # - libwebp-base=1.4.0
  # - libxcb=1.17.0
  # - libxcrypt=4.4.36
  # - libxkbcommon=1.0.3
  # - libxml2=2.12.7
  # - libzlib=1.3.1
  # - lz4-c=1.9.4
  # - markupsafe=2.1.3
  # - matplotlib-base=3.9.2
  # - mpmath=1.3.0
  # - mysql=5.7.20
  # - ncurses=6.4
  # - nettle=3.6
  # - networkx=3.3
  # - nomkl=3.0
  # - numexpr=2.8.7
  # - numpy=1.26.4
  # - numpy-base=1.26.4
  # - ocl-icd=2.3.2
  # - openblas=0.3.28
  - opencv=4.10.0
  # - openexr=3.2.2
  # - openh264=2.4.1
  # - openjpeg=2.5.2
  # - openssl=3.3.2
  # - packaging=24.1
  # - pandas=2.2.2
  # - patsy=0.5.6
  # - pcre2=10.44
  # - pillow=10.4.0
  - pip=24.3
  # - pixman=0.43.2
  # - psutil=5.9.0
  # - pthread-stubs=0.4
  # - pugixml=1.14
  # - py-cpuinfo=9.0.0
  # - py-opencv=4.10.0
  # - pybind11-abi=5
  # - pycparser=2.22
  # - pyparsing=3.1.4
  # - pysocks=1.7.1
  # - python=3.12.2
  # - python-dateutil=2.9.0
  - python-dotenv=0.21.0
  # - python-tzdata=2024.2
  # - python_abi=3.12
  # - pytorch=2.4.0
  # - pytz=2024.2
  # - pyyaml=6.0.1
  # - readline=8.2
  # - requests=2.32.3
  # - scipy=1.13.1
  # - seaborn=0.13.2
  # - seaborn-base=0.13.2
  # - setuptools=75.1.0
  # - six=1.16.0
  # - sleef=3.7
  # - snappy=1.2.1
  # - sqlite=3.31.1
  # - statsmodels=0.14.2
  # - svt-av1=2.2.1
  # - sympy=1.13.2
  # - tbb=2021.13.0
  # - tk=8.6.13
  # - torchvision=0.18.1
  # - tqdm=4.66.5
  # - typing_extensions=4.11.0
  # - tzdata=2024a
  # - ultralytics=8.2.103
  # - unicodedata2=15.1.0
  # - urllib3=2.2.3
  # - wayland=1.23.1
  # - wayland-protocols=1.37
  # - werkzeug=3.0.3
  # - wheel=0.44.0
  # - x264=1!164.3095
  # - x265=3.5
  # - xorg-libice=1.1.1
  # - xorg-libsm=1.2.4
  # - xorg-libx11=1.8.10
  # - xorg-libxau=1.0.11
  # - xorg-libxdmcp=1.1.3
  # - xorg-libxext=1.3.4
  # - xorg-libxfixes=6.0.0
  # - xorg-libxrender=0.9.11
  # - xorg-xorgproto=2024.1
  # - xz=5.4.6
  - yacs=0.1.6
  # - yaml=0.2.5
  # - zlib=1.3.1
  # - zstandard=0.19.0
  # - zstd=1.5.6
  - pip:
      - dill==0.3.9
      - torchvision==0.21.0
      - ultralytics==8.3.78
      - ultralytics-thop==2.0.14
